image: golang:1.13

cache:
    paths:
        - /apt-cache
        - /go/src/github.com
        - /go/src/golang.org
        - /go/src/google.golang.org
        - /go/src/gopkg.in
stages:
  - test
  - build

before_script:
  - mkdir -p /go/src/gitlab.com/delivc /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/delivc/identity
  - ln -s /go/src/gitlab.com/delivc /go/src/_/builds/delivc
  - go get golang.org/x/lint/golint
  - make deps

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
  - master

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make